#!/bin/sh
#Git Merge and Push

currentBranch=`git branch | grep \*`
trimmedBranch=`echo "$currentBranch" | sed -e 's/\*//g' | sed -e 's/\ //g'`

if [ $trimmedBranch = "master" ]; then

  gpall "$1"

else

  ga #git add -A
  gc "$1" #git commit -m "$1"

  git checkout master
  git merge "$trimmedBranch"

  gp #git push
  git checkout "$trimmedBranch"

fi

